# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'countryPickerGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests

#Logic for network request
'''
base_url = "https://www.apicountries.com/countries"

def get_countries():
    response = requests.get(base_url)
    print(response)

    if response.status_code == 200:
        country_data = response.json()
        country_names = sorted([country["name"] for country in country_data])
        return country_names
    else:
        print(f"Failed to retrieve {response.status_code}")
        return []

country_names = get_countries()

if country_names:
    print(f"First country: {country_names[0]}")
else:
    print("No countries found.")

'''


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(265, 357)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboB1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboB1.setGeometry(QtCore.QRect(30, 60, 211, 31))
        self.comboB1.setCurrentText("")
        self.comboB1.setObjectName("comboB1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(30, 20, 61, 31))
        self.label1.setObjectName("label1")
        self.imageLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel1.setGeometry(QtCore.QRect(180, 20, 61, 31))
        self.imageLabel1.setScaledContents(True)
        self.imageLabel1.setObjectName("imageLabel1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 265, 21))
        self.menubar.setObjectName("menubar")
        self.menuCountries = QtWidgets.QMenu(self.menubar)
        self.menuCountries.setObjectName("menuCountries")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCountries.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setText(_translate("MainWindow", "Selected:"))
        self.imageLabel1.setText(_translate("MainWindow", "---"))
        self.menuCountries.setStatusTip(_translate("MainWindow", "Select a country"))
        self.menuCountries.setTitle(_translate("MainWindow", "Countries"))
        self.menuInfo.setStatusTip(_translate("MainWindow", "Exercise information"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
